#!/bin/bash

dmenu_run \
    -b -i \
    -p "$" \
    -fn "Iosevka Curly Slab-Bold:size=15:bold" \
    -nb "#000000" -nf "#93a1a1" -sb "#b58900" -sf "#002b36"
# rofi -show run -matching regex -font "Iosevka Slab Bold 12" -hide-scrollbar -disable-history -lines 5
