#!/bin/bash

dmenu_run \
    -b -i \
    -p ":" \
    -fn "Iosevka Slab-Bold:size=13:bold" \
    -nb "#000000" -nf "#93a1a1" -sb "#b58900" -sf "#002b36"
    # -nb "#002b36" -nf "#657b83" -sb "#b58900" -sf "#002b36"
# rofi -show run -font "Iosevka Slab Bold 16" -hide-scrollbar -disable-history
