#!/bin/bash

command -v git >/dev/null 2>&1 || exit

git_status=$(git status -uno 2>/dev/null | head -n2 | perl -pe 's/\n/\\n/g')
git_branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)

if [[ $git_branch != "" ]]; then
    modified=$(git diff --no-ext-diff --quiet --exit-code || echo '*')
    behind=$(echo $git_status | grep 'behind' >/dev/null 2>&1 && echo '-')
    ahead=$(echo $git_status | grep 'ahead' >/dev/null 2>&1 && echo '+')
    echo " (${git_branch}${modified}${behind}${ahead})"
fi
