#!/bin/bash

plus() {
    pamixer -i 5
}

minus() {
    pamixer -d 5
}

mute() {
    pamixer -t
}

percent() {
    pamixer --get-volume
}

notify() {
    muted=""
    if [[ "$(pamixer --get-mute)" == "true" ]]; then
        muted=" (muted)"
    fi
    notify-send -a Volume -h string:x-canonical-private-synchronous:pavol Volume "$(percent)%$muted"
}

case "$1" in
    plus)
        plus
        notify
        ;;
    minus)
        minus
        notify
        ;;
    mute)
        mute
        notify
        ;;
    get)
        get
        ;;
    percent)
        percent
        ;;
esac
