#!/bin/bash

plus() {
    pamixer -i 3
}

minus() {
    pamixer -d 3
}

mute() {
    pamixer -t
}

percent() {
    pamixer --get-volume
}

notify() {
    sink=$(pamixer --get-default-sink | tail -n1 | cut -f3- -d' ' | tr -d '"')
    case "$sink" in
        *Anker\ Lightning*)
            sink="Audeze LCD-i4"
            ;;
        *Renoir\ Radeon*)
            sink="HDMI out"
            ;;
        *Speaker*)
            sink="Speakers"
            ;;
    esac

    muted=""
    if [[ "$(pamixer --get-mute)" == "true" ]]; then
        muted=" (muted)"
    fi
    notify-send -a Volume -h string:x-canonical-private-synchronous:pavol \
        "Volume" \
        "$(percent)%$muted\n$sink"
}

case "$1" in
    plus)
        plus
        notify
        ;;
    minus)
        minus
        notify
        ;;
    mute)
        mute
        notify
        ;;
    get)
        get
        ;;
    percent)
        percent
        ;;
esac
