#!/bin/bash

files=$(find ~/.tmux/resurrect -iname "tmux_resurrect*" | sort -rh | tail -n+2 | xargs)

if [[ "$files" != "" ]]; then
  for file in $files; do
    rm -v "$file"
  done
else
  echo "No cleanup needed"
fi

echo "Last is $(realpath ~/.tmux/resurrect/last)"
