#!/bin/bash

command -v add-colours >/dev/null 2>&1 && source add-colours

_BASEDIR=$HOME/.dotfiles

if ! command -v stow >/dev/null 2>&1; then
    echo "Binary \`stow\` not found, please install GNU Stow." >&2
    exit 1
fi

if (( "$#" < 2 )); then
    echo "Usage: ${0##*/} <directory> <file> [<file>...]" >&2
    exit 1
fi

_dir="$1"
_fullpath="$_BASEDIR/$_dir"
_stowdir="${_dir%%/*}"

if [[ ! -d "$_fullpath" ]]; then
    echo "No such directory: $_dir." >&2
    exit 1
fi

echo -e "${_bold}${_white}==> Adding to directory: ${_stowdir}${_reset}"
shift

for file in "$@"; do
    if [[ ! -f "$file" ]]; then
        echo "File does not exist: $file." >&2
        continue
    fi
    if [[ -L "$file" ]]; then
        echo "File is a symlink, ignoring: $file." >&2
        continue
    fi
    mv -v "$file" "$_fullpath"
done

pushd "$_BASEDIR" >/dev/null
stow -v "$_stowdir"
popd >/dev/null
